In [1]:
import pandas as pd
import os

In [2]:
folder=r"D:\Cyclistic Case Study\Raw Datasets"

In [9]:
files = os.listdir(folder)
files

['202507-divvy-tripdata.csv',
 '202508-divvy-tripdata.csv',
 '202509-divvy-tripdata.csv',
 '202510-divvy-tripdata.csv',
 '202511-divvy-tripdata.csv',
 '202512-divvy-tripdata.csv',
 '202601-divvy-tripdata.csv',
 '202602-divvy-tripdata.csv',
 '202603-divvy-tripdata.csv',
 '202604-divvy-tripdata.csv',
 '202605-divvy-tripdata.csv',
 '202606-divvy-tripdata.csv']

In [10]:
csv_files = [f for f in files if f.endswith('.csv')]
csv_files

['202507-divvy-tripdata.csv',
 '202508-divvy-tripdata.csv',
 '202509-divvy-tripdata.csv',
 '202510-divvy-tripdata.csv',
 '202511-divvy-tripdata.csv',
 '202512-divvy-tripdata.csv',
 '202601-divvy-tripdata.csv',
 '202602-divvy-tripdata.csv',
 '202603-divvy-tripdata.csv',
 '202604-divvy-tripdata.csv',
 '202605-divvy-tripdata.csv',
 '202606-divvy-tripdata.csv']

In [11]:
len(csv_files)

12

In [12]:
import os

os.listdir(folder)

['202507-divvy-tripdata.csv',
 '202508-divvy-tripdata.csv',
 '202509-divvy-tripdata.csv',
 '202510-divvy-tripdata.csv',
 '202511-divvy-tripdata.csv',
 '202512-divvy-tripdata.csv',
 '202601-divvy-tripdata.csv',
 '202602-divvy-tripdata.csv',
 '202603-divvy-tripdata.csv',
 '202604-divvy-tripdata.csv',
 '202605-divvy-tripdata.csv',
 '202606-divvy-tripdata.csv']

In [13]:
import os

print(os.path.exists(folder))

True

In [14]:
import os

for f in os.listdir(folder):
    print(f, os.path.isfile(os.path.join(folder, f)))

202507-divvy-tripdata.csv True
202508-divvy-tripdata.csv True
202509-divvy-tripdata.csv True
202510-divvy-tripdata.csv True
202511-divvy-tripdata.csv True
202512-divvy-tripdata.csv True
202601-divvy-tripdata.csv True
202602-divvy-tripdata.csv True
202603-divvy-tripdata.csv True
202604-divvy-tripdata.csv True
202605-divvy-tripdata.csv True
202606-divvy-tripdata.csv True

In [15]:
df = pd.read_csv(os.path.join(folder, csv_files[0]))

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,455D43BD91D73437,classic_bike,2025-07-05 17:15:08.456,2025-07-05 17:25:47.079,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member
1,9D4A6B723ECD98CA,classic_bike,2025-07-01 13:57:38.878,2025-07-01 14:06:35.780,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.607100,41.809855,-87.606755,member
2,C57044CF523302ED,classic_bike,2025-07-31 16:49:28.142,2025-07-31 17:15:28.999,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member
3,AFD35552E6685B6E,electric_bike,2025-07-17 09:36:21.058,2025-07-17 09:46:54.706,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.949473,-87.646453,41.968812,-87.657659,member
4,C0582EBAA6CED519,classic_bike,2025-07-02 18:43:45.213,2025-07-02 18:57:06.687,Theater on the Lake,CHI00420,Sheffield Ave & Wellington Ave,CHI00274,41.926277,-87.630834,41.936253,-87.652662,member

In [16]:
df.shape

(763432, 13)

In [17]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [18]:
all_data=[]

for file in csv_files:
    path=os.path.join(folder, file)
    df = pd.read_csv(path)
    all_data.append(df)

In [19]:
bike_trips = pd.concat(all_data, ignore_index=True)

In [21]:
bike_trips.shape

(5932349, 13)

In [22]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5932349 entries, 0 to 5932348
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 588.4+ MB

In [23]:
bike_trips.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1257513
start_station_id      1257513
end_station_name      1321680
end_station_id        1321680
start_lat                   0
start_lng                   0
end_lat                  5606
end_lng                  5606
member_casual               0
dtype: int64

In [24]:
bike_trips["ride_id"].duplicated().sum()

35

In [25]:
bike_trips.describe(include="all")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
count,5932349,5932349,5932349,5932349,4674836,4674836,4610669,4610669,5.932349e+06,5.932349e+06,5.926743e+06,5.926743e+06,5932349
unique,5932314,2,5931099,5929142,1965,1977,1992,2005,NaN,NaN,NaN,NaN,2
top,3767A2E3310A5B0B,electric_bike,2026-05-24 17:11:29.609,2025-08-18 19:30:47.144,Navy Pier,CHI01747,Navy Pier,CHI01747,NaN,NaN,NaN,NaN,member
freq,2,4012477,2,23,60880,69750,60277,69095,NaN,NaN,NaN,NaN,3815715
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.190420e+01,-8.764671e+01,4.190462e+01,-8.764706e+01,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.442902e-02,2.711569e-02,4.459233e-02,2.734684e-02,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.164850e+01,-8.789000e+01,4.151000e+01,-8.810000e+01,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.188241e+01,-8.766000e+01,4.188275e+01,-8.766000e+01,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.189962e+01,-8.764242e+01,4.190000e+01,-8.764288e+01,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.193000e+01,-8.763000e+01,4.193000e+01,-8.763000e+01,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.207000e+01,-8.752000e+01,4.221000e+01,-8.737000e+01,NaN

In [26]:
bike_trips["started_at"] = pd.to_datetime(bike_trips["started_at"])
bike_trips["ended_at"] = pd.to_datetime(bike_trips["ended_at"])

In [27]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5932349 entries, 0 to 5932348
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 588.4+ MB

In [32]:
bike_trips["ride_length"] = round((
    bike_trips["ended_at"] - bike_trips["started_at"]
).dt.total_seconds() / 60,2)

In [33]:
bike_trips[["started_at", "ended_at", "ride_length"]].head()

               started_at                ended_at  ride_length
0 2025-07-05 17:15:08.456 2025-07-05 17:25:47.079        10.64
1 2025-07-01 13:57:38.878 2025-07-01 14:06:35.780         8.95
2 2025-07-31 16:49:28.142 2025-07-31 17:15:28.999        26.01
3 2025-07-17 09:36:21.058 2025-07-17 09:46:54.706        10.56
4 2025-07-02 18:43:45.213 2025-07-02 18:57:06.687        13.36

In [37]:
bike_trips["ride_length"].head()

0    10.64
1     8.95
2    26.01
3    10.56
4    13.36
Name: ride_length, dtype: float64

In [38]:
bike_trips["ride_length"].describe()

count    5.932349e+06
mean     1.577000e+01
std      5.347706e+01
min     -5.479000e+01
25%      5.360000e+00
50%      9.370000e+00
75%      1.647000e+01
max      1.559950e+03
Name: ride_length, dtype: float64

In [39]:
bike_trips[bike_trips["ride_length"] < 0]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
2939528,5D010AFEA6850513,electric_bike,2025-11-02 01:52:37.475,2025-11-02 01:13:24.728,Pine Grove Ave & Wellington Ave,CHI02158,Wilton Ave & Addison St,CHI02055,41.936510,-87.641190,41.947459,-87.653216,member,-39.21
2941076,D1E5316AD88ECD45,classic_bike,2025-11-02 01:50:39.702,2025-11-02 01:14:04.164,Clark St & Ida B Wells Dr,CHI00216,Paulina St & Division St,CHI00244,41.875933,-87.630585,41.903553,-87.670429,casual,-36.59
2943070,3AF2F8908C9386F8,classic_bike,2025-11-02 01:57:57.512,2025-11-02 01:33:52.225,State St & Chicago Ave,CHI01772,Ravenswood Ave & Berteau Ave,CHI00471,41.896617,-87.628579,41.957921,-87.673567,member,-24.09
2957966,19386939ECD81B33,electric_bike,2025-11-02 01:55:34.399,2025-11-02 01:21:31.873,Broadway & Sheridan Rd,CHI00476,NaN,NaN,41.952833,-87.649993,41.960000,-87.740000,member,-34.04
2966334,083534D28DA37F72,classic_bike,2025-11-02 01:17:57.001,2025-11-02 01:05:27.752,Clark St & Grace St,CHI00301,Grace St & Central Ave,CHI01799,41.950780,-87.659172,41.949533,-87.767265,member,-12.49
3010919,4A659F1BB40EDBF7,electric_bike,2025-11-02 01:55:38.177,2025-11-02 01:04:35.315,Keystone Ave & Montrose Ave,CHI00643,Lynch Ave & Elston Ave,CHI02000,41.961108,-87.728970,41.980960,-87.761490,casual,-51.05
3036472,DA5386E5759667EC,electric_bike,2025-11-02 01:51:31.704,2025-11-02 01:05:47.339,Racine Ave & Belmont Ave,CHI00411,Dearborn St & Division St,CHI02125,41.939743,-87.658865,41.904300,-87.629910,member,-45.74
3041930,985A3462DAACFFCF,classic_bike,2025-11-02 01:59:07.835,2025-11-02 01:05:19.214,Seminary Ave & Belden Ave,CHI02106,Sedgwick St & Webster Ave,CHI00487,41.923390,-87.655990,41.922167,-87.638888,member,-53.81
3061853,434E3D11ABA96891,electric_bike,2025-11-02 01:59:40.156,2025-11-02 01:08:51.303,Public Rack - Olmstead Ave & Oliphant Ave,CHI01613,Milwaukee Ave & Highland Ave,CHI02015,42.002311,-87.817095,41.996360,-87.786740,casual,-50.81
3071671,9288498F5630E3AD,electric_bike,2025-11-02 01:49:48.360,2025-11-02 01:02:40.976,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NaN,NaN,41.901315,-87.677409,41.870000,-87.680000,casual,-47.12
3071688,12E0A9A586A45DE3,electric_bike,2025-11-02 01:49:41.788,2025-11-02 01:02:30.041,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NaN,NaN,41.901315,-87.677409,41.870000,-87.680000,member,-47.20
3073056,222A5E8650C55311,electric_bike,2025-11-02 01:55:51.266,2025-11-02 01:01:50.026,W Armitage Ave & N Sheffield Ave,CHI00836,NaN,NaN,41.917805,-87.653449,41.910000,-87.640000,member,-54.02
3081824,83995E751A0DB5D5,electric_bike,2025-11-02 01:50:50.530,2025-11-02 01:01:15.026,Paulina St & Division St,CHI00244,Kedzie Ave & Milwaukee Ave,CHI00378,41.903553,-87.670429,41.929714,-87.707988,member,-49.59
3114878,120BC0544C3B92E4,classic_bike,2025-11-02 01:41:32.055,2025-11-02 01:08:10.359,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-33.36
3114982,4446901DBDE0531B,classic_bike,2025-11-02 01:45:25.021,2025-11-02 01:08:08.134,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-37.28
3126068,ED8C9D500F271C3D,classic_bike,2025-11-02 01:57:24.553,2025-11-02 01:02:44.165,Racine Ave & Randolph St,CHI00320,Ogden Ave & Chicago Ave,CHI00275,41.884081,-87.656921,41.896362,-87.654061,member,-54.67
3127426,4976DE4C5F1AA516,electric_bike,2025-11-02 01:56:44.152,2025-11-02 01:06:51.164,NaN,NaN,Sedgwick St & Huron St,CHI00241,41.920000,-87.640000,41.894666,-87.638437,member,-49.88
3127803,3301C8D1FF15E4CE,electric_bike,2025-11-02 01:58:08.316,2025-11-02 01:16:43.649,Manor Ave & Leland Ave,CHI00633,Damen Ave & Division St,CHI00318,41.965875,-87.700825,41.903266,-87.678435,member,-41.41
3149618,A66DEC9146C488BF,electric_bike,2025-11-02 01:50:17.559,2025-11-02 01:07:46.445,NaN,NaN,Wilton Ave & Addison St,CHI02055,42.000000,-87.670000,41.947459,-87.653216,member,-42.52
3151887,595AED6AB9A66E8F,classic_bike,2025-11-02 01:51:37.195,2025-11-02 01:18:08.912,Michigan Ave & Oak St,CHI00252,Sedgwick St & Webster Ave,CHI00487,41.900960,-87.623777,41.922167,-87.638888,member,-33.47
3155427,5740B9AA6176D32C,classic_bike,2025-11-02 01:59:56.801,2025-11-02 01:05:09.113,Western Blvd & 48th Pl,CHI00735,Campbell Ave & 51st St,CHI01918,41.805661,-87.683392,41.800940,-87.686760,member,-54.79
3174991,A61B896123C0D647,classic_bike,2025-11-02 01:28:03.715,2025-11-02 01:05:17.029,Sacramento Ave & Lyndale St,CHI02126,Rush St & Cedar St,CHI00537,41.922350,-87.702410,41.902309,-87.627691,casual,-22.78
3178243,093B3FC8E465DA4A,electric_bike,2025-11-02 01:52:58.523,2025-11-02 01:04:31.464,NaN,NaN,Wabash Ave & Roosevelt Rd,CHI00524,41.860000,-87.620000,41.867227,-87.625961,member,-48.45
3179718,C89AFBD919D615FD,classic_bike,2025-11-02 01:51:49.264,2025-11-02 01:18:50.977,Sedgwick St & Huron St,CHI00241,Southport Ave & Irving Park Rd,CHI00481,41.894666,-87.638437,41.954177,-87.664358,member,-32.97
3189231,8BF21DA40F846779,electric_bike,2025-11-02 01:57:17.456,2025-11-02 01:26:23.644,Campbell Ave & North Ave,CHI00341,Campbell Ave & North Ave,CHI00341,41.910535,-87.689556,41.910535,-87.689556,member,-30.90
3190643,01C21B340CC1EEDA,classic_bike,2025-11-02 01:50:43.657,2025-11-02 01:03:13.912,California Ave & Milwaukee Ave,CHI00307,Paulina Ave & North Ave,CHI00258,41.922695,-87.697153,41.909855,-87.669930,casual,-47.50
3191785,F87FA50B8D40FA97,electric_bike,2025-11-02 01:54:25.185,2025-11-02 01:10:50.859,NaN,NaN,Michigan Ave & Madison St,CHI01915,41.880000,-87.640000,41.882134,-87.625125,casual,-43.57
3224366,5F7692C857079901,electric_bike,2025-11-02 01:54:17.357,2025-11-02 01:13:50.718,Clark St & Leland Ave,CHI00461,NaN,NaN,41.967088,-87.667291,41.960000,-87.660000,member,-40.44
3257358,E37AEB3E9CE2343E,electric_bike,2025-11-02 01:56:26.465,2025-11-02 01:03:08.183,Broadway & Roscoe Ave,CHI02153,NaN,NaN,41.943600,-87.645320,41.960000,-87.650000,member,-53.30

In [40]:
bike_trips[bike_trips["ride_length"] < 0].shape

(29, 14)

In [41]:
bike_trips[bike_trips["ride_length"] > 1440].shape

(5539, 14)

In [42]:
bike_trips["day_of_week"] = bike_trips["started_at"].dt.day_name()

In [43]:
bike_trips["month"] = bike_trips["started_at"].dt.month_name()

In [44]:
bike_trips["hour"] = bike_trips["started_at"].dt.hour

bike_trips["day_type"] = bike_trips["day_of_week"].isin(
    ["Saturday", "Sunday"]
).map({True: "Weekend", False: "Weekday"})

In [45]:
bike_trips[
    ["started_at", "ride_length", "day_of_week", "month", "hour", "day_type"]
].head()

               started_at  ride_length day_of_week month  hour day_type
0 2025-07-05 17:15:08.456        10.64    Saturday  July    17  Weekend
1 2025-07-01 13:57:38.878         8.95     Tuesday  July    13  Weekday
2 2025-07-31 16:49:28.142        26.01    Thursday  July    16  Weekday
3 2025-07-17 09:36:21.058        10.56    Thursday  July     9  Weekday
4 2025-07-02 18:43:45.213        13.36   Wednesday  July    18  Weekday

In [46]:
bike_trips.groupby("member_casual")["ride_length"].agg(["count", "mean", "median", "max"])

                 count       mean  median      max
member_casual
casual         2116634  21.728711   11.16  1559.95
member         3815715  12.464621    8.59  1559.90

In [47]:
bike_trips_clean = bike_trips[
    (bike_trips["ride_length"] >= 0) &
    (bike_trips["ride_length"] <= 1440)
].copy()

In [49]:
bike_trips_clean.shape

(5926781, 18)

In [50]:
bike_trips_clean.groupby("member_casual")["ride_length"].agg(
    ["count", "mean", "median", "max"]
)

                 count       mean  median      max
member_casual
casual         2112111  18.570855   11.13  1439.98
member         3814670  12.065628    8.58  1439.90

In [51]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

bike_trips_clean["season"] = bike_trips_clean["started_at"].dt.month.apply(get_season)

In [53]:
bike_trips_clean["season"]

0          Summer
1          Summer
2          Summer
3          Summer
4          Summer
            ...
5932344    Summer
5932345    Summer
5932346    Summer
5932347    Summer
5932348    Summer
Name: season, Length: 5926781, dtype: object

In [54]:
season_analysis = bike_trips_clean.groupby(
    ["member_casual", "season"]
).size().reset_index(name="rides")

season_analysis

  member_casual  season    rides
0        casual    Fall   587212
1        casual  Spring   463516
2        casual  Summer   967634
3        casual  Winter    93749
4        member    Fall  1128415
5        member  Spring   954326
6        member  Summer  1346330
7        member  Winter   385599

In [55]:
hour_analysis = bike_trips_clean.groupby(
    ["member_casual", "hour"]
).size().reset_index(name="rides")

hour_analysis.sort_values(
    ["member_casual", "rides"],
    ascending=[True, False]
)

   member_casual  hour   rides
17        casual    17  201168
16        casual    16  186052
18        casual    18  172826
15        casual    15  161703
14        casual    14  145339
13        casual    13  138695
12        casual    12  133913
19        casual    19  129775
11        casual    11  112678
20        casual    20   93965
10        casual    10   88135
21        casual    21   80184
8         casual     8   74722
9         casual     9   73086
22        casual    22   69072
7         casual     7   52055
23        casual    23   49699
0         casual     0   43111
6         casual     6   28318
1         casual     1   28120
2         casual     2   18247
5         casual     5   12864
3         casual     3   10171
4         casual     4    8213
41        member    17  411479
40        member    16  360904
42        member    18  319773
32        member     8  278840
39        member    15  254106
43        member    19  221640
31        member     7  215413
36        member    12  201125
38        member    14  200475
37        member    13  197839
33        member     9  176520
35        member    11  176281
44        member    20  154530
34        member    10  150928
45        member    21  120194
30        member     6  108296
46        member    22   87451
47        member    23   54544
29        member     5   37010
24        member     0   35220
25        member     1   21479
26        member     2   12859
28        member     4    9392
27        member     3    8372

In [56]:
bike_trips_clean[
    bike_trips_clean["member_casual"] == "casual"
]["start_station_name"].value_counts().head(10)

start_station_name
Navy Pier                             46735
DuSable Lake Shore Dr & Monroe St     32768
Michigan Ave & Oak St                 22823
DuSable Lake Shore Dr & North Blvd    20173
Millennium Park                       18433
Shedd Aquarium                        17202
Theater on the Lake                   16189
Dusable Harbor                        15107
Michigan Ave & 8th St                 10887
Montrose Harbor                       10562
Name: count, dtype: int64

In [57]:
bike_type_analysis = (
    bike_trips_clean
    .groupby(["member_casual", "rideable_type"])
    .size()
    .reset_index(name="rides")
)

bike_type_analysis

  member_casual  rideable_type    rides
0        casual   classic_bike   630410
1        casual  electric_bike  1481701
2        member   classic_bike  1283911
3        member  electric_bike  2530759

In [58]:
bike_trips_clean.to_csv(
    r"D:\Cyclistic Case Study\Output\bike_trips_clean.csv",
    index=False
)